Repository pytorch/examples, pull requests merged in 2022-08, with the labels that each got.

#1028 refine imagenet dummy part of #1011
  imagenet/README.md
  imagenet/main.py
Labels: cla signed

#1034 Fix for NCCL backend, all_reduce performed on GPU when available
  imagenet/main.py
Labels: bug, cla signed, distributed, training

#1043 fix: prevent "context has already been set" error in mnist_hogwild example
  mnist_hogwild/main.py
Labels: cla signed

#1044 Fix flaky dcgan test by using fake data
  run_python_examples.sh
Labels: cla signed, testing
