Repository pytorch/examples, pull requests merged in 2022-09, with the labels that each got.

#1058 Update
  docs/source/index.rst
Labels: cla signed

#1051 Fixed RL examples to work with new gym API
  reinforcement_learning/actor_critic.py
  reinforcement_learning/reinforce.py
Labels: cla signed

#1048 Update actor_critic.py typo
  reinforcement_learning/actor_critic.py
Labels: cla signed

#1057 fix imagenet nondeterminism when seed is set (#1056)
  imagenet/main.py
Labels: cla signed

#1045 Fix the wrong link in issues-template
  .github/ISSUE_TEMPLATE/bug_template.md
Labels: cla signed

#1018 Add mps device
  dcgan/README.md
  dcgan/main.py
  fast_neural_style/README.md
  fast_neural_style/neural_style/neural_style.py
  imagenet/main.py
  legacy/snli/train.py
  mnist/main.py
  mnist_hogwild/main.py
  run_python_examples.sh
  siamese_network/main.py
  super_resolution/README.md
  super_resolution/main.py
  vae/README.md
  vae/main.py
  word_language_model/README.md
  word_language_model/main.py
Labels: enhancement, cla signed

#1061 Revert "Add mps device"
  dcgan/README.md
  dcgan/main.py
  fast_neural_style/README.md
  fast_neural_style/neural_style/neural_style.py
  imagenet/main.py
  legacy/snli/train.py
  mnist/main.py
  mnist_hogwild/main.py
  run_python_examples.sh
  siamese_network/main.py
  super_resolution/README.md
  super_resolution/main.py
  vae/README.md
  vae/main.py
  word_language_model/README.md
  word_language_model/main.py
Labels: cla signed

#1064 Add mps device
  dcgan/README.md
  dcgan/main.py
  fast_neural_style/README.md
  fast_neural_style/neural_style/neural_style.py
  imagenet/main.py
  legacy/snli/train.py
  mnist/main.py
  mnist_hogwild/main.py
  run_python_examples.sh
  siamese_network/main.py
  super_resolution/README.md
  super_resolution/main.py
  vae/README.md
  vae/main.py
  word_language_model/README.md
  word_language_model/main.py
Labels: enhancement, cla signed, mac

#1066 Mac enhancement .gitignore to ignore .DS_*
  .gitignore
Labels: cla signed

#1067 Add code for DDP tutorial series [PR 1 / 3]
  distributed/ddp-tutorial-series/README.md
  distributed/ddp-tutorial-series/datautils.py
  distributed/ddp-tutorial-series/multigpu.py
  distributed/ddp-tutorial-series/multigpu_torchrun.py
  distributed/ddp-tutorial-series/multinode.py
  distributed/ddp-tutorial-series/requirements.txt
  distributed/ddp-tutorial-series/single_gpu.py
Labels: cla signed

#1068 Add code for DDP tutorial series [PR 2 / 3]
  distributed/ddp-tutorial-series/slurm/config.yaml.template
  distributed/ddp-tutorial-series/slurm/sbatch_run.sh
  distributed/ddp-tutorial-series/slurm/setup_pcluster_slurm.md
Labels: cla signed

#1069 Add code for DDP tutorial series [PR 3 / 3]
  distributed/minGPT-ddp/README.md
  distributed/minGPT-ddp/mingpt/char_dataset.py
  distributed/minGPT-ddp/mingpt/data/input.txt
  distributed/minGPT-ddp/mingpt/gpt2_train_cfg.yaml
  distributed/minGPT-ddp/mingpt/main.py
  distributed/minGPT-ddp/mingpt/model.py
  distributed/minGPT-ddp/mingpt/slurm/config.yaml.template
  distributed/minGPT-ddp/mingpt/slurm/sbatch_run.sh
  distributed/minGPT-ddp/mingpt/slurm/setup_pcluster_slurm.md
  distributed/minGPT-ddp/mingpt/trainer.py
  distributed/minGPT-ddp/requirements.txt
  docs/source/index.rst
Labels: cla signed

#1070 Added mps option in generate.py
  word_language_model/generate.py
Labels: cla signed

#1073 Fix device mismatch issue in #1071
  imagenet/main.py
Labels: cla signed, distributed
