Repository pytorch/examples, pull requests merged in 2022-03, with the labels that each got.

#949 #71844 Migrate default branch to main.
  .github/workflows/main.yml
  distributed/rpc/batch/reinforce.py
  distributed/rpc/rl/main.py
  distributed/rpc/rnn/rnn.py
Labels: cla signed

#953 Update requirements.txt
  reinforcement_learning/requirements.txt
Labels: cla signed

#860 [*.py] Rename "Arguments:" to "Args:"
  distributed/rpc/batch/reinforce.py
  distributed/rpc/rl/main.py
Labels: cla signed

#386 Normalized loss in actor-critic and REINFORCE examples.
  reinforcement_learning/actor_critic.py
  reinforcement_learning/reinforce.py
Labels: reinforcement learning

#970 updated dcgan docs
  dcgan/README.md
Labels: cla signed

#971 Revert "Normalized loss in actor-critic and REINFORCE examples."
  reinforcement_learning/actor_critic.py
  reinforcement_learning/reinforce.py
Labels: cla signed

#972 clarifying what pytorch/examples is and how to contribute
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/doc_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: cla signed

#974 Update run_python_examples.sh
  run_python_examples.sh
Labels: cla signed

#982 Closes #771. Fix vague description on batch size calculation in imagenet.
  imagenet/main.py
Labels: cla signed

#864 fast neural style: run onnxmodel using onnxruntime
  fast_neural_style/neural_style/neural_style.py
Labels: cla signed, onnx

#859 Use PyTorch Step Scheduler
  imagenet/main.py
Labels: cla signed, triaged wait

#977 Change imagenet data script to include training data
  imagenet/README.md
  imagenet/extract_ILSVRC.sh
  imagenet/main.py
Labels: cla signed

#986 Update RPC link, etc.
  README.md
Labels: cla signed
