Repository pytorch/examples, pull requests merged in 2022-10, with the labels that each got.

#1076 Add set_epoch and fix args in DDP-series example
  distributed/ddp-tutorial-series/multigpu.py
  distributed/ddp-tutorial-series/multigpu_torchrun.py
  distributed/ddp-tutorial-series/multinode.py
  distributed/minGPT-ddp/mingpt/trainer.py
Labels: cla signed

#1083 Speed-up to O(1) from O(N) of the computation of each return in REINFORCE
  reinforcement_learning/reinforce.py
Labels: enhancement, reinforcement learning

#1084 Add map_location when loading model checkpoint
  distributed/ddp-tutorial-series/multinode.py
Labels: cla signed

#752 Example of MNIST using RNN
  mnist_rnn/README.md
  mnist_rnn/main.py
  mnist_rnn/requirements.txt
Labels: vision

#1086 add mnist_rnn to test script for CI
  mnist_rnn/main.py
  run_python_examples.sh
Labels: cla signed, testing
